### ISSUE TITLE
Cannot read property '0' of null

### ISSUE THREAD

**Issue by chappjc** [stkb/vscode-rewrap#14]
Trying to rewrap any comments in a particular Go file, I get this.  Just one file, others work fine.  I can take comments from that file into another file and they wrap fine.

[Extension Host] TypeError: Cannot read property '0' of null
    at new Section (C:\Users\user.vscode\extensions\stkb.rewrap-0.6.2\out\src\Section.js:19:66)
    at BasicLanguage.findSections (C:\Users\user.vscode\extensions\stkb.rewrap-0.6.2\out\src\BasicLanguage.js:35:38)
    at wrapSomething (C:\Users\user.vscode\extensions\stkb.rewrap-0.6.2\out\src\Main.js:33:28)
    at C:\Users\user.vscode\extensions\stkb.rewrap-0.6.2\out\src\Main.js:15:20
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:29051
    at e.edit (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:24633)
    at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:29017
    at t.$executeContributedCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:11:4834)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:22905)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:30449)

**Comment by stkb** [comment]
Sorry for the late reply; I've been away for a few days.

This is a weird error and I really need access to that file to determine what's causing it. Would it be possible for you to add the file as an attachment here or email it to me (my address is on my profile page)?

If that's not possible, you could try these:
1. Create a new .go file in vscode and copy the whole contents of the affected file into the new. Does it still fail then?
2. Or, remove a few sections at a time from the file to try to work out where it starts going wrong

**Comment by chappjc** [comment]
Unfortunately that version of the file is long gone and I haven't seen this error recently.

However, at the time, I did copy the contents of the file into another new file and it still had the issue, so it wasn't a file write/perms issue.  Can't say much else though.  I think it must have been some offending part of the file that vscode-rewrap didn't like.

**Comment by stkb** [comment]
Ok. I'll leave this open in case we or someone can find a reproducing example.

**Comment by stkb** [comment]
Going to assume this is the same issue as #11 (it was the same error message).
